name: Run Scrapers (simple)

on:
  schedule:
    - cron: "12 9 * * *"   # 09:12 UTC
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scraper-inmobiliario

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output folder exists
        run: |
          mkdir -p data/raw

      - name: Run scrapers
        run: |
          python -m src.scrapers.main_scraper

      - name: Upload outputs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output-${{ github.run_id }}
          path: |
            scraper-inmobiliario/data/raw/**/*.json
            scraper-inmobiliario/data/raw/**/*.jsonl
          if-no-files-found: ignore
          retention-days: 7
