name: Run Scrapers (simple)

on:
  schedule:
    # Corre todos los días a las 09:12 UTC (~05:12 en Santiago en invierno).
    - cron: "12 9 * * *"
  workflow_dispatch: {}  # permite ejecutarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output folder exists
        run: |
          mkdir -p data/raw

      - name: Run scrapers
        run: |
          cd scraper-inmobiliario
          python -m src.main


      # Opcional: sube lo que se haya generado (si no hay archivos, NO falla)
      - name: Upload outputs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output-${{ github.run_id }}
          path: |
            data/raw/**/*.json
            data/raw/**/*.jsonl
          if-no-files-found: ignore
          retention-days: 7
